### ISSUE TITLE
Text To Speech

### ISSUE THREAD

**Issue by GlobalGamer2015** [GlobalGamer2015/RUM-Bot#17]
Currently not possible, as most TTS services require a cost per call.

**Comment by GlobalGamer2015** [comment]
> Also an option for a dollar amount requirement to kick off the TTS so for example if you pay 1-4 dollars no TTS but 5+ it'll read your message.
> A drop down box of generic voices to use for TTS readouts.
D-Pad Chat

**Comment by thelabcat** [comment]
Could you do it locally with eSpeak, perhaps? It’s FOSS and cross-platform, though I don’t know if their license allows you to redistribute it bundled with RumBot. An alternative if it doesn’t could be to have a field where the user can specify the eSpeak executable location, and the bot runs it with the proper options to get WAV data back, which it then sends to OBS.

**Comment by tinyplayerss** [comment]
> Could you do it locally with [eSpeak](https://github.com/espeak-ng/espeak-ng) perhaps? It’s FOSS and cross-platform, though I don’t know if their license allows you to redistribute it bundled with RumBot. An alternative if it doesn’t could be to have a field where the user can specify the eSpeak executable location, and the bot runs it with the proper options to get WAV data back, which it then sends to OBS.

This is What there License Says.
![image](https://github.com/GlobalGamer2015/RUM-Bot/assets/123846642/0bc4b78c-acae-49e3-8a4d-6e587a24a81f)

**Comment by GlobalGamer2015** [comment]
Implemented TTS in dev version.
