### ISSUE TITLE
pls look at the error code

### ISSUE THREAD

**Issue by marlon99rocks** [GlobalGamer2015/RUM-Bot#30]
here is the error im having dont know why it not working it say 600 code and misspell
[error.log](https://github.com/GlobalGamer2015/RUM-Bot/files/13062346/error.log)

**Comment by GlobalGamer2015** [comment]
It is not working because it is not connecting to OBS.

**Comment by marlon99rocks** [comment]
i can use it on switcher scene but the other one not working use scene source

**Comment by marlon99rocks** [comment]
so what is the issue should i get the older version

**Comment by GlobalGamer2015** [comment]
This error: `Error displaying alert: OBSWebSocketError: No scene items were found in the specified scene by that name or offset.` means one of your scene names are misspelled.
Double check your scene names.

From the looks of the log.
You have the Follower, Subscriber and Rant scenes as "webcam".
They should be separate scenes made just for your alerts.

![image](https://github.com/GlobalGamer2015/RUM-Bot/assets/19220996/8689bcfb-4b90-4d45-9dcc-19d7b92e90b7)

**Comment by GlobalGamer2015** [comment]
Scene source requires the scenes to be inside of your Main Scene, example is above.

**Comment by GlobalGamer2015** [comment]
Here is a tutorial made by @VapinGamers.
https://rumble.com/v3m4d7g-rum-bot-2.0-how-to-add-live-alerts-to-live-streams.html

**Comment by marlon99rocks** [comment]
Error displaying alert: OBSWebSocketError: No scene items were found in the specified scene by that name or offset.
    at C:\Users\User\Desktop\alerts2.03\node_modules\obs-websocket-js\dist\json.cjs:512:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doAlert_AltMain3Scene (C:\Users\User\Desktop\alerts2.03\index.js:755:37)
    at async Timeout.showAlert [as _onTimeout] (C:\Users\User\Desktop\alerts2.03\index.js:933:17) {
  code: 600
}
You have a mispelled scene name:
Main Scene:  Webcam
Main Scene:  Screen
Main Scene:  Card
Main Scene:  Android
Follower Scene:  webcam
Subscriber Scene:  webcam
Rant Scene:  webcam

**Comment by GlobalGamer2015** [comment]
> This error: `Error displaying alert: OBSWebSocketError: No scene items were found in the specified scene by that name or offset.` means one of your scene names are misspelled. Double check your scene names.
> 
> From the looks of the log. You have the Follower, Subscriber and Rant scenes as "webcam". They should be separate scenes made just for your alerts.
> 
> ![image](https://user-images.githubusercontent.com/19220996/277145553-8689bcfb-4b90-4d45-9dcc-19d7b92e90b7.png)

**Comment by marlon99rocks** [comment]
thanks got it working now thanks

**Comment by marlon99rocks** [comment]
![Desktop 22-10-2023 3-08-13 PM-671](https://github.com/GlobalGamer2015/RUM-Bot/assets/23298994/23db5922-6d7f-4647-8b10-3a5cda5469ab)
![Desktop 22-10-2023 3-08-15 PM-953](https://github.com/GlobalGamer2015/RUM-Bot/assets/23298994/dbb41710-44d7-41af-9172-5ed08013152d)
![Desktop 22-10-2023 3-08-22 PM-284](https://github.com/GlobalGamer2015/RUM-Bot/assets/23298994/ada555df-e839-4f4f-bb53-d2bfb0bff27d)
![Desktop 22-10-2023 3-08-25 PM-153](https://github.com/GlobalGamer2015/RUM-Bot/assets/23298994/44265d16-bcad-4139-bc87-97918a2dc097)
![Desktop 22-10-2023 3-08-26 PM-728](https://github.com/GlobalGamer2015/RUM-Bot/assets/23298994/9c5259f1-3477-4acb-b73c-3a3ed4fef647)

**Comment by GlobalGamer2015** [comment]
I'm glad it is working for you now, closing issue.
