### ISSUE TITLE
Rum Live Alerts App Won't open anymore...

### ISSUE THREAD

**Issue by PsuedoR** [GlobalGamer2015/RUM-Bot#40]
### Issue Summary
Hello, I've been using RumBot for about 2 months now, but just a few days back I got this weird "Unhandled Error" with the description "SyntaxError: Unexpected token" paired with it. Then I click OK and get another error titled: "Unhandled Promise Rejection" with the description of
"Error: ERR_FAILED (-2) loading 'http://localhost:9843/software_settings'
    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:213:1360)"
I've uninstalled and reinstalled RumBot to see if that would fix the issue, but it does not work as the error just repeats.

### Steps to Reproduce

1. Open the app.
2. First Error Message.
3. Second error Message.

Any relevant information.
![Unhandled Error](https://github.com/GlobalGamer2015/RUM-Bot/assets/58041528/7ccec60e-84fd-48f1-a075-8d4d7c269e0a)
![image](https://github.com/GlobalGamer2015/RUM-Bot/assets/58041528/d987d67d-fcd1-468b-b22e-f57df31c7c51)

### Technical details
Based on the description of the second error it seems to be something related to JavaScript.

**Comment by GlobalGamer2015** [comment]
What version do you have installed?

You can go here to find the .exe and get the version.
C:\Users\YourUsername\AppData\Local\RUM Live Alerts App
![image](https://github.com/GlobalGamer2015/RUM-Bot/assets/19220996/cb23f90d-1618-4326-a8de-6a4d7e8b1310)

**Comment by PsuedoR** [comment]
Thanks for the reply,
![image](https://github.com/GlobalGamer2015/RUM-Bot/assets/58041528/9f144ba8-5327-41e8-bfb2-bd26f86fa07b)
here's my version

**Comment by GlobalGamer2015** [comment]
Do you have Discord or Guilded?
If so, send me a DM, "GG2015".

**Comment by PsuedoR** [comment]
got discord, send me full name

**Comment by GlobalGamer2015** [comment]
![image](https://github.com/GlobalGamer2015/RUM-Bot/assets/19220996/b3c99f7f-23ec-42f2-aad6-4a363903ffce)

**Comment by PsuedoR** [comment]
Can't send friend request, and I can't seem to create a DM with your username.

**Comment by GlobalGamer2015** [comment]
What is your Discord username?

**Comment by PsuedoR** [comment]
Borderlands

**Comment by GlobalGamer2015** [comment]
Solved by giving a default PersonalInformation.json file.
Uploading this for the future for others to use and redirect to this comment.
[PersonalInformation.json](https://github.com/GlobalGamer2015/RUM-Bot/files/13698838/PersonalInformation.json)
