### ISSUE TITLE
Adding Testing Features for Sending a Test Message in Chat

### ISSUE THREAD

**Issue by tinyplayerss** [GlobalGamer2015/RUM-Bot#43]
### Test Message For Chat
Think of this You want to Customize the Chat on OBS Studio and you want to Customize the CSS, well You can't do that Easily You would need to Copy and Paste a Popout Chat URL of an Existing Stream with Active Chatters to Customize the Chat Overlay this is not an issue but its a tad bit Difficult to do so.

### Instead of Copy and Pasting
We can just have a Simple "Test Message" Button to Send a Test Message in the Chat Overlay.

### Alternatives?
All though you could add these Features we would like to have something like a Dedicated Customization Option to Customize the Chat Overlay.

**Comment by GlobalGamer2015** [comment]
When you add a issue, check and make sure there are no other issues, features, or bugs similar to what you are about to post.

[The Ability to Send a TEST Message in Chat When Wanting to See New Changes when Editing the CSS on OBS #46](https://github.com/GlobalGamer2015/RUM-Bot/issues/46)
