### ISSUE TITLE
Error message; Can't Start

### ISSUE THREAD

**Issue by OllOver** [GlobalGamer2015/RUM-Bot#44]
### Issue Summary

Selected "Use SLOBS"
Filled the information correctly. Once I press "Start," keep getting error message "OBS Port numeric field is empty. Definition: OBS WebSocket Server Port."
I know it's empty because I selected and wanted SLOBS.
Do I have to have OBS?

### Steps to Reproduce

1. 
2. 
3. 

Any relevant information.

**Comment by VapinGamers** [comment]
OllOver thanks for posting your comment. All you need to do is in the OBS portion of the UI, type 4455 in the port box and it will work just fine. If you need anything else let me know.

**Comment by OllOver** [comment]
> OllOver thanks for posting your comment. All you need to do is in the OBS portion of the UI, type 4455 in the port box and it will work just fine. If you need anything else let me know.

Thank you for the response, VapinGamers. It worked.
