### ISSUE TITLE
Question: How to make Username pop up?

### ISSUE THREAD

**Issue by OllOver** [GlobalGamer2015/RUM-Bot#45]
### Issue Summary

Hello, I followed step by step installing and setting up the follow alerts. Everything works perfectly, but when I get a new follower the display is still the text I displayed instead of the new follower's username. Was I suppose to install something for that?
### Steps to Reproduce

1. 
2. 
3. 

Any relevant information.

**Comment by GlobalGamer2015** [comment]
Either VapinGamers or I can help you with this on Discord, due to the issue being multiple things.
https://discord.gg/sDfjAhw4NK
