### ISSUE TITLE
The Ability to Send a TEST Message in Chat When Wanting to See New Changes when Editing the CSS on OBS

### ISSUE THREAD

**Issue by tinyplayerss** [GlobalGamer2015/RUM-Bot#46]
# Chat Overlay (TEST Message)
The Reason for this is to be able to Test the BOT or You have some CSS code to put into Good use, With OBS Studio's CSS Editor on browser sources You can edit or add CSS selectors from the Localhost:300/Chat (Example) to see Your new Changes in OBS without having to Go live to Test it or Have to Get someone else's Chat URL to see the Changes, a Quick and Easy solution would be to add a Send TEST Message button on the Chat Window of the Bot.

**Comment by GlobalGamer2015** [comment]
Coded in Dev version.
