### ISSUE TITLE
Problem with the password field i think. I got an error TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by Switched2BSD** [GlobalGamer2015/RUM-Bot#51]
Problem with the password field i think. I got an error TypeError: Cannot read property 'value' of undefined
The same thing happens on linux and windows

It used to work but not anymore !
   maybe i should try to use an older version ?

**Comment by GlobalGamer2015** [comment]
If you can join the discord, we can help you out.
I tried to replicate it and I was not able to.

[https://discord.gg/WgmSaCRZSq](https://discord.gg/WgmSaCRZSq)
